In [ ]:
import json
import numpy as np
import networkx as nx
import pandas as pd
import matplotlib.pyplot as plt
from networkx.readwrite import json_graph

%matplotlib inline

In [ ]:
from IngestionModule.twitterlistener import Dummy 

help(Dummy)

In [ ]:
import _generateGraph as gg

help(gg.HashtagGraph())

In [ ]:
import _loadData as l

help(l.LoadData())

### Loading up the HTT dataset

In [ ]:
# Loading and Specifying data types for csv
edgelist = pd.read_csv("/Users/akshaykulkarni/Downloads/twitter/edgelist", 
                       sep = "\t", names=["source","target"], dtype={'source': 'int', 'target': 'int'})

# Sampling the graph with rudimentary Max_Filter (can look into more elegant graph smapling methods)
e_filter = edgelist.query('`source` <= 100 & `target` <= 100')
e_filter = e_filter.sort_values(by=['source', 'target'])
e_filter

In [ ]:
# Preloaded demo karate-community graph
g = nx.karate_club_graph()
fig1, ax1 = plt.subplots(1, 1, figsize=(8, 6));
nx.draw_networkx(g, ax=ax1)

# Twitter graph
G = nx.from_pandas_edgelist(e_filter, "source", "target")
fig, ax = plt.subplots(1, 1, figsize=(10, 10));
nx.draw_networkx(G, ax=ax)

#### Ironically NetworkX has a 2d spectral graphing function which Draws the graph G with a spectral 2D layout.

Using the unnormalized Laplacian, the layout shows possible clusters of nodes which are an approximation of the ratio cut. The positions are the entries of the second and third eigenvectors corresponding to the ascending eigenvalues starting from the second one.

In [ ]:
fig, ax = plt.subplots(1, 1, figsize=(10, 10));
print("Sampled Spectral graph ")
nx.draw_spectral(G, ax=ax)


##  Creating JSON dumps of graph object data for JS stuff

In [ ]:
# defining custom exporting function
def exportToJSON(Graph, filename):
    nodes = [{'name': str(i)}
             for i in Graph.nodes()]
    links = [{'source': u[0], 'target': u[1]}
             for u in Graph.edges()]
    with open(filename+'.json', 'w') as f:
        json.dump({'nodes': nodes, 'links': links},
                  f, indent=4,)

In [ ]:
exportToJSON(G,"graph")
# exportToJSON(g,"graph1")

In [ ]:
# turns out networkx has fuctionality but the above func can be used to export minimal data 
# Converting graph objects into JSON to be read by D3
from networkx.readwrite import json_graph
data = json_graph.node_link_data(g)
with open('karate.json', 'w') as f:
    json.dump(data, f, indent=4)
    

from networkx.readwrite import json_graph
data = json_graph.node_link_data(G)
with open('HTT.json', 'w') as f:
    json.dump(data, f, indent=4)

# D3 visualisation  stuff

In [ ]:
# D3 visualisations can be rendered in an ipynb notebook by injecting JS code in html cells ...
# for some god damn fucking reason its working just fine with the example karate graph 
# but does not render our HTT twitter graph I HAVE NO IDEA WHY ... i've been wrestling with d3 since Atlanta .. 
# though i have managed to view our graphs in d3 in other code cells just not in our notebook here.


# run html cell then run the next JS cell the graph will come as output of the html cell

In [ ]:
%%html
<div id="d3-container"> </div>

<style>

.node {stroke: #fff; stroke-width: 1.5px;}
.link {stroke: #999; stroke-opacity: .6;}

</style>

In [ ]:
%%html
<!DOCTYPE html>
<meta charset="utf-8">
<style>

.links line {
  stroke: #999;
  stroke-opacity: 0.6;
}

.nodes circle {
  stroke: black	;
  stroke-width: 0px;
}

</style>
<svg width="800" height="500"></svg>
<script src="https://d3js.org/d3.v4.min.js"></script>
<script>

//create somewhere to put the force directed graph
var svg = d3.select("svg"),
    width = +svg.attr("width"),
    height = +svg.attr("height");
    
var radius = 5; 

var nodes_data =  [
    {"name": "Lillian", "sex": "F"},
    {"name": "Gordon", "sex": "M"},
    {"name": "Sylvester", "sex": "M"},
    {"name": "Mary", "sex": "F"},
    {"name": "Helen", "sex": "F"},
    {"name": "Jamie", "sex": "M"},
    {"name": "Jessie", "sex": "F"},
    {"name": "Ashton", "sex": "M"},
    {"name": "Duncan", "sex": "M"},
    {"name": "Evette", "sex": "F"},
    {"name": "Mauer", "sex": "M"},
    {"name": "Fray", "sex": "F"},
    {"name": "Duke", "sex": "M"},
    {"name": "Baron", "sex": "M"},
    {"name": "Infante", "sex": "M"},
    {"name": "Percy", "sex": "M"},
    {"name": "Cynthia", "sex": "F"},
    {"name": "Feyton", "sex": "M"},
    {"name": "Lesley", "sex": "F"},
    {"name": "Yvette", "sex": "F"},
    {"name": "Maria", "sex": "F"},
    {"name": "Lexy", "sex": "F"},
    {"name": "Peter", "sex": "M"},
    {"name": "Ashley", "sex": "F"},
    {"name": "Finkler", "sex": "M"},
    {"name": "Damo", "sex": "M"},
    {"name": "Imogen", "sex": "F"}
    ]


var links_data = [
	{"source": "Sylvester", "target": "Gordon", "type":"A" },
    {"source": "Sylvester", "target": "Lillian", "type":"A" },
    {"source": "Sylvester", "target": "Mary", "type":"A"},
    {"source": "Sylvester", "target": "Jamie", "type":"A"},
    {"source": "Sylvester", "target": "Jessie", "type":"A"},
    {"source": "Sylvester", "target": "Helen", "type":"A"},
    {"source": "Helen", "target": "Gordon", "type":"A"},
    {"source": "Mary", "target": "Lillian", "type":"A"},
    {"source": "Ashton", "target": "Mary", "type":"A"},
    {"source": "Duncan", "target": "Jamie", "type":"A"},
    {"source": "Gordon", "target": "Jessie", "type":"A"},
    {"source": "Sylvester", "target": "Fray", "type":"E"},
    {"source": "Fray", "target": "Mauer", "type":"A"},
    {"source": "Fray", "target": "Cynthia", "type":"A"},
    {"source": "Fray", "target": "Percy", "type":"A"},
    {"source": "Percy", "target": "Cynthia", "type":"A"},
    {"source": "Infante", "target": "Duke", "type":"A"},
    {"source": "Duke", "target": "Gordon", "type":"A"},
    {"source": "Duke", "target": "Sylvester", "type":"A"},
    {"source": "Baron", "target": "Duke", "type":"A"},
    {"source": "Baron", "target": "Sylvester", "type":"E"},
    {"source": "Evette", "target": "Sylvester", "type":"E"},
    {"source": "Cynthia", "target": "Sylvester", "type":"E"},
    {"source": "Cynthia", "target": "Jamie", "type":"E"},
    {"source": "Mauer", "target": "Jessie", "type":"E"},
    {"source": "Duke", "target": "Lexy", "type":"A"},
    {"source": "Feyton", "target": "Lexy", "type":"A"},
    {"source": "Maria", "target": "Feyton", "type":"A"},
    {"source": "Baron", "target": "Yvette", "type":"E"},
    {"source": "Evette", "target": "Maria", "type":"E"},
    {"source": "Cynthia", "target": "Yvette", "type":"E"},
    {"source": "Maria", "target": "Jamie", "type":"E"},
    {"source": "Maria", "target": "Lesley", "type":"E"},
    {"source": "Ashley", "target": "Damo", "type":"A"},
    {"source": "Damo", "target": "Lexy", "type":"A"},
    {"source": "Maria", "target": "Feyton", "type":"A"},
    {"source": "Finkler", "target": "Ashley", "type":"E"},
    {"source": "Sylvester", "target": "Maria", "type":"E"},
    {"source": "Peter", "target": "Finkler", "type":"E"},
    {"source": "Ashley", "target": "Gordon", "type":"E"},
    {"source": "Maria", "target": "Imogen", "type":"E"}
    
]


//set up the simulation and add forces  
var simulation = d3.forceSimulation()
					.nodes(nodes_data);
                              
var link_force =  d3.forceLink(links_data)
                        .id(function(d) { return d.name; });            
         
var charge_force = d3.forceManyBody()
    .strength(-100); 
    
var center_force = d3.forceCenter(width / 2, height / 2);  
                      
simulation
    .force("charge_force", charge_force)
    .force("center_force", center_force)
    .force("links",link_force);

        
//add tick instructions: 
simulation.on("tick", tickActions );

//add encompassing group for the zoom 
var g = svg.append("g")
    .attr("class", "everything");

//draw lines for the links 
var link = g.append("g")
      .attr("class", "links")
    .selectAll("line")
    .data(links_data)
    .enter().append("line")
      .attr("stroke-width", 2)
      .style("stroke", linkColour);        

//draw circles for the nodes 
var node = g.append("g")
        .attr("class", "nodes") 
        .selectAll("circle")
        .data(nodes_data)
        .enter()
        .append("circle")
        .attr("r", radius)
        .attr("fill", circleColour);
 
 
//add drag capabilities  
var drag_handler = d3.drag()
	.on("start", drag_start)
	.on("drag", drag_drag)
	.on("end", drag_end);	
	
drag_handler(node);


//add zoom capabilities 
var zoom_handler = d3.zoom()
    .on("zoom", zoom_actions);

zoom_handler(svg);     

/** Functions **/

//Function to choose what color circle we have
//Let's return blue for males and red for females
function circleColour(d){
	if(d.sex =="M"){
		return "blue";
	} else {
		return "pink";
	}
}

//Function to choose the line colour and thickness 
//If the link type is "A" return green 
//If the link type is "E" return red 
function linkColour(d){
	if(d.type == "A"){
		return "green";
	} else {
		return "red";
	}
}

//Drag functions 
//d is the node 
function drag_start(d) {
 if (!d3.event.active) simulation.alphaTarget(0.3).restart();
    d.fx = d.x;
    d.fy = d.y;
}

//make sure you can't drag the circle outside the box
function drag_drag(d) {
  d.fx = d3.event.x;
  d.fy = d3.event.y;
}

function drag_end(d) {
  if (!d3.event.active) simulation.alphaTarget(0);
  d.fx = null;
  d.fy = null;
}

//Zoom functions 
function zoom_actions(){
    g.attr("transform", d3.event.transform)
}

function tickActions() {
    //update circle positions each tick of the simulation 
       node
        .attr("cx", function(d) { return d.x; })
        .attr("cy", function(d) { return d.y; });
        
    //update link positions 
    link
        .attr("x1", function(d) { return d.source.x; })
        .attr("y1", function(d) { return d.source.y; })
        .attr("x2", function(d) { return d.target.x; })
        .attr("y2", function(d) { return d.target.y; });
} 
</script>

In [ ]:
%%javascript
require.config({paths: {d3: "https://d3js.org/d3.v3.min"}});
require(["d3"], function(d3) {
    var width = 600,
        height = 600;

    var color = d3.scale.category10();

    // Creating a force-directed dynamic graph layout.
    var force = d3.layout.force()
        .charge(-500)
        .linkDistance(50)
        .size([width, height]);

    var svg = d3.select("#d3-container").select("svg")
    if (svg.empty()) {
        svg = d3.select("#d3-container").append("svg")
                    .attr("width", width)
                    .attr("height", height);
    }

    // load the JSON network file.
    d3.json("karate.json", function(error, tgraph) {
        // Within this block, the network has been loaded and stored
        // load the nodes and links into the force-directed
        // graph and initialise the dynamics.
        force.nodes(tgraph.nodes)
            .links(tgraph.links)
            .start();

        // We create a <line> SVG element for each link
        // in the graph.
        var link = svg.selectAll(".link")
            .data(tgraph.links)
            .enter().append("line")
            .attr("class", "link");

        // create a <circle> SVG element for each node
        // in the graph, and we specify a few attributes.
        var node = svg.selectAll(".node")
            .data(tgraph.nodes)
            .enter().append("circle")
            .attr("class", "node")
            .attr("r", 5)  // radius
            .call(force.drag);

        // The label each node its node number from the networkx graph.
        node.append("title")
            .text(function(d) { return d.id; });

        // bind the positions of the SVG elements
        // to the positions of the dynamic force-directed graph,
        // at each time step.
        force.on("tick", function() {
            link.attr("x1", function(d) { return d.source.x; })
                .attr("y1", function(d) { return d.source.y; })
                .attr("x2", function(d) { return d.target.x; })
                .attr("y2", function(d) { return d.target.y; });

            node.attr("cx", function(d) { return d.x; })
                .attr("cy", function(d) { return d.y; });
        });
    });
});

-------------

# COVID-19 Mined Dataset

In [ ]:
import json
import numpy as np
import networkx as nx
import pandas as pd
import matplotlib.pyplot as plt
from networkx.readwrite import json_graph

covid_raw = pd.read_csv("Data/Hashtag_Raw_Data/COVID19_hashtags7.csv").drop(["Unnamed: 0"], axis =1)
display(covid_raw)

print(covid_raw.nunique())

covid_raw['hashtag_id'] = covid_raw.groupby(['hashtag_x']).ngroup()
covid_raw.columns = ["tweet_id", "hashtag_name","tweet_hashtag_count", "hashtag_id"]

display(covid_raw)
covid_nodelist = covid_raw.drop_duplicates(['hashtag_name','hashtag_id'])[['hashtag_name','hashtag_id']].copy()

covid_nodelist = covid_nodelist.sort_values(by=['hashtag_id'])

covid_nodelist.to_csv("COVID19_NodeList.csv", index= False)

covid_nodelist

In [ ]:
from itertools import combinations

covid_edgelist_src = covid_raw[["tweet_id", "hashtag_id"]]

list_of_edges = []

# Createing edges
for i, group in covid_edgelist_src.groupby(['tweet_id'])['hashtag_id']:
    # generate all combinations without replacement 
    # from the group of similar column pairs
    for u, v in combinations(group, 2):           
        list_of_edges.append(sorted([u, v]))
        


covid_edgelist = pd.DataFrame(list_of_edges, columns=["Source","Target"])


covid_edgelist = covid_edgelist.sort_values(by=['Source',"Target"])

covid_edgelist = covid_edgelist.groupby(covid_edgelist.columns.tolist()).size().reset_index().\
    rename(columns={0:'Edge_Freq'})

print(covid_edgelist.shape)
covid_edgelist

In [ ]:
# Twitter graph
# temp = covid_edgelist.query('`Source` <= 50 & `Target` <= 50')
# display(temp)
C = nx.from_pandas_edgelist(covid_edgelist, "Source", "Target",['Edge_Freq'])
fig, ax = plt.subplots(1, 1, figsize=(20, 20));
nx.draw(C, ax=ax)

In [ ]:
test = covid_nodelist.set_index('hashtag_id') 
test['Communities'] = np.arange(3509)

test

In [ ]:
attrs = test.to_dict('index')
attrs
nx.set_node_attributes(C, attrs)

In [ ]:
C.nodes[1299]

In [ ]:
import networkx as nx
def connected_component_subgraphs(G):
    for c in nx.connected_components(G):
        yield G.subgraph(c).copy()
   

G.subgraph(c).copy() for c in connected_components(G)

connected_nodes = max(connected_component_subgraphs(C), key=len)

print(len(C.nodes))
print(len(connected_nodes.nodes))

In [ ]:
connected_nodes.nodes[1299]['hashtag_name']

In [ ]:
#Saving

covid_nodelist.to_csv("COVID19_NodeList.csv", index= False)
covid_edgelist.to_csv("COVID19_EdgeList.csv", index= False)

## Experimental Stuff

Libs
- pyvis ( main opt)
- graphistry ( high capacity opt )
- d3g (bs)

In [ ]:
!pwd

import os
os.chdir('..')
!pwd

In [ ]:
covid_raw = pd.read_csv("Data/Hashtag_Raw_Data/COVID19_hashtags7.csv").drop(["Unnamed: 0"], axis =1)
display(covid_raw)

print(covid_raw.nunique())

covid_raw['hashtag_id'] = covid_raw.groupby(['hashtag_x']).ngroup()
covid_raw.columns = ["tweet_id", "hashtag_name","tweet_hashtag_count", "hashtag_id"]

display(covid_raw)
covid_nodelist = covid_raw.drop_duplicates(['hashtag_name','hashtag_id'])[['hashtag_name','hashtag_id']].copy()

covid_nodelist = covid_nodelist.sort_values(by=['hashtag_id'])

covid_nodelist.to_csv("COVID19_NodeList.csv", index= False)

covid_nodelist

In [ ]:
from itertools import combinations

covid_edgelist_src = covid_raw[["tweet_id", "hashtag_id"]]

test = covid_raw.query('`hashtag_id` <= 5')
display(test)

list_of_edges = []

# Createing edges
for i, group in test.groupby(['tweet_id'])['hashtag_id']:
    # generate all combinations without replacement 
    # from the group of similar column pairs
    for u, v in combinations(group, 2):           
        list_of_edges.append(sorted([u, v]))
        


covid_edgelist = pd.DataFrame(list_of_edges, columns=["Source","Target"])


covid_edgelist = covid_edgelist.sort_values(by=['Source',"Target"])



print(covid_edgelist.shape)
covid_edgelist

In [ ]:
from itertools import combinations

covid_edgelist_src = covid_raw[["tweet_id", "hashtag_id"]]

test = covid_raw.query('`hashtag_id` <= 5')
display(test)

list_of_edges = []

# Createing edges
for i, group in covid_edgelist_src.groupby(['tweet_id'])['hashtag_id']:
    # generate all combinations without replacement 
    # from the group of similar column pairs
    for u, v in combinations(group, 2):           
        list_of_edges.append([u, v])
        


covid_edgelist = pd.DataFrame(list_of_edges, columns=["Source","Target"])


covid_edgelist = covid_edgelist.sort_values(by=['Source',"Target"])



print(covid_edgelist.shape)
covid_edgelist.drop_duplicates(['Source','Target'])

In [ ]:
island = pd.read_csv("/Users/akshaykulkarni/Downloads/connected_edges.csv")
C = nx.from_pandas_edgelist(island, "Source", "Target")
# fig, ax = plt.subplots(1, 1, figsize=(20, 20))
# nx.draw_kamada_kawai(C, ax=ax)

In [ ]:
from networkx.readwrite import json_graph
data = json_graph.node_link_data(C)
with open('island.json', 'w') as f:
    json.dump(data, f, indent=4)

In [ ]:
from pyvis.network import Network as pyNet
import networkx as nx
G = pyNet(notebook = True)
G.show_buttons(filter_=['physics'])
G.from_nx(C)
G.show('island2.html')

In [ ]:
island[island['Source'] == 1299]

In [1]:
import pandas as pd
nodes = pd.read_csv('data/Island/connected_nodes.csv')

In [2]:
nodes[nodes['hashtag_id'].isin([2313,2810,2824,2865])]

          hashtag_name  hashtag_id
1164         education        2313
1447      ncssethebest        2810
1459  newteacheradvice        2824
1480  oldteacheradvice        2865

In [16]:
 x= nodes[nodes['hashtag_id'].isin([17, 56, 112, 121, 129, 137, 150, 151, 173, 176, 198, 202, 263, 463, 559, 620, 644, 645, 646, 650, 658, 731, 774, 841, 873, 919, 923, 924, 981, 988, 990, 1050, 1204, 1207, 1214, 1256, 1259, 1290, 1299, 1311, 1355, 1437, 1449, 1452, 1478, 1485, 1499, 1509, 1512, 1534, 1537, 1543, 1544, 1555, 1562, 1565, 1572, 1594, 1630, 1645, 1647, 1652, 1688, 1689, 1696, 1720, 1792, 1798, 1812, 1848, 1950, 1975, 1976, 1989, 1997, 2064, 2083, 2090, 2123, 2129, 2135, 2164, 2239, 2292, 2309, 2425, 2474, 2507, 2539, 2548, 2551, 2598, 2602, 2657, 2791, 2838, 2882, 2885, 2905, 2906, 2907, 2913, 2990, 3028, 3038, 3087, 3121, 3144, 3186, 3195, 3279, 3302, 3315, 3367, 3380, 3434, 3461, 3474, 3477, 3483, 3487]
)]

In [22]:
pd.set_option('display.max_rows', 500)


x.to_csv("1299.csv")

In [7]:
comm_35 = [735,1111,1563,1889,1980,1985,2052,2099,2131,2148,2380,2381,2389,2515,2519,2608,2877,2988,3054,3196,3234,3326,3339,3455]
nodes[nodes['hashtag_id'].isin(comm_35)]

            hashtag_name  hashtag_id
351          HowCanIHelp         735
535               Nature        1111
768     StrongerTogether        1563
943            academics        1889
986           begenerous        1980
989               bekind        1985
1031        businessnews        2052
1056             charity        2099
1071   closingequitygaps        2131
1078           community        2148
1202             fitness        2380
1203  flatteningthecurve        2381
1207       follow4follow        2389
1277        homelessness        2515
1280         homeworking        2519
1332                itfc        2608
1484       opportunities        2877
1545              pretty        2988
1573             regrann        3054
1650              squash        3196
1676    strongertogether        3234
1726             toronto        3326
1731               trail        3339
1792               write        3455

In [23]:
GN_41= [621, 1292, 1898, 2422, 2648, 2649, 3382]
nodes[nodes['hashtag_id'].isin(GN_41)]

     hashtag_name  hashtag_id
295           GPU         621
625   QLOCdragons        1292
946   agoraphobia        1898
1225       gamers        2422
1356       korona        2648
1357  koronavirus        2649
1757    videogame        3382

In [ ]:
GN_40= [334, 1604, 2737, 2738, 2802, 2814, 2815, 3101]
nodes[nodes['hashtag_id'].isin(GN_40)]

In [ ]:
nodes[nodes['hashtag_id'].isin([1265,1938,2287,2288,2327,2550,2682,3427])]

In [4]:
comm_35 = [735,1111,1563,1889,1980,1985,2052,2099,2131,2148,2380,2381,2389,2515,2519,2608,2877,2988,3054,3196,3234,3326,3339,3455]
nodes[nodes['hashtag_id'].isin(comm_35)]

            hashtag_name  hashtag_id
351          HowCanIHelp         735
535               Nature        1111
768     StrongerTogether        1563
943            academics        1889
986           begenerous        1980
989               bekind        1985
1031        businessnews        2052
1056             charity        2099
1071   closingequitygaps        2131
1078           community        2148
1202             fitness        2380
1203  flatteningthecurve        2381
1207       follow4follow        2389
1277        homelessness        2515
1280         homeworking        2519
1332                itfc        2608
1484       opportunities        2877
1545              pretty        2988
1573             regrann        3054
1650              squash        3196
1676    strongertogether        3234
1726             toronto        3326
1731               trail        3339
1792               write        3455

In [67]:
CNM_37 =[777, 2268, 1627, 2378, 2849, 2445, 2743, 2848, 2938, 3286]
GN_39= [777, 1627, 2268, 2378, 2445, 2743, 2848, 2849, 2938, 3286]



nodes[nodes['hashtag_id'].isin(GN_39)]




MED_DF = pd.concat([nodes[nodes['hashtag_id'].isin(CNM_37)],nodes[nodes['hashtag_id'].isin(GN_39)]],axis =1)
MED_DF.to_csv('CNM37vsGN39.csv')

In [68]:
CNM_9 =[21, 2265, 2605, 3069, 496, 1360, 1372, 1385, 649, 1340, 1524, 1638, 2248, 2347, 2541, 2604, 2748, 2953, 1467, 2127, 2346]
GN_33 =[496, 649, 818, 1310, 1340, 1348, 1360, 1372, 1385, 1467, 1524, 1638, 1838, 2127, 2248, 2541, 2604, 2748, 2953]


# display(nodes[nodes['hashtag_id'].isin(CNM_9)],nodes[nodes['hashtag_id'].isin(GN_33)])

MED_DF = pd.concat([nodes[nodes['hashtag_id'].isin(CNM_9)],nodes[nodes['hashtag_id'].isin(GN_33)]],axis =1)

MED_DF.to_csv('CNM9vsGN33.csv')
# MED_DF.to_csv('_comparison.csv')

In [ ]:
CNM_20 = [378, 1435, 1440, 1731]

In [5]:
GN_40= [334, 1604, 2737, 2738, 2802, 2814, 2815, 3101]
nodes[nodes['hashtag_id'].isin(GN_40)]

         hashtag_name  hashtag_id
153       ClickOnCare         334
791     TaiwanCanHelp        1604
1406            masks        2737
1407          masques        2738
1444          namaste        2802
1451          netflix        2814
1452  netflixandchill        2815
1603        sanitizer        3101

In [ ]:
import json

with open('GN_SY_Test_1.json') as f:
    data = json.load(f)

print(data)

In [37]:
gn_comms = {}
for i in data['nodes']:
    gn_comms[i['id']] = i['CNM_Label']

In [38]:
gn_comms

{1: 15,
 2228: 15,
 2828: 15,
 3175: 15,
 6: 27,
 2589: 27,
 3098: 27,
 7: 2,
 2092: 2,
 2448: 2,
 10: 9,
 74: 9,
 196: 9,
 319: 2,
 399: 9,
 1048: 9,
 1088: 20,
 1338: 9,
 1719: 9,
 1768: 9,
 1785: 9,
 1964: 9,
 2157: 7,
 2301: 9,
 2801: 9,
 3013: 9,
 3295: 9,
 12: 20,
 2491: 20,
 2622: 20,
 3409: 20,
 13: 16,
 614: 16,
 15: 11,
 2306: 11,
 2411: 11,
 2412: 11,
 17: 1,
 1299: 1,
 1555: 1,
 1792: 1,
 3461: 1,
 18: 8,
 1258: 8,
 2522: 6,
 2546: 8,
 2898: 8,
 3274: 14,
 21: 2,
 2265: 2,
 2605: 2,
 3069: 2,
 22: 12,
 1544: 1,
 2706: 12,
 26: 36,
 3320: 36,
 27: 31,
 87: 31,
 1285: 31,
 2726: 31,
 2937: 31,
 28: 18,
 737: 18,
 1855: 18,
 2294: 18,
 29: 8,
 3096: 8,
 3233: 8,
 38: 12,
 227: 26,
 713: 12,
 42: 9,
 417: 9,
 1356: 9,
 1999: 9,
 49: 7,
 64: 7,
 1483: 7,
 56: 1,
 129: 1,
 1534: 1,
 57: 4,
 69: 4,
 60: 7,
 62: 7,
 1236: 7,
 2892: 7,
 3350: 7,
 61: 7,
 577: 7,
 63: 26,
 845: 26,
 846: 38,
 1557: 26,
 67: 2,
 802: 2,
 813: 2,
 1505: 23,
 68: 12,
 2695: 12,
 117: 4,
 445: 4,
 697: 4,
 905: 4,
 1494: 4,
 1607: 4,
 1875: 4,
 1885: 4,
 70: 4,
 234: 9,
 1368: 9,
 1765: 9,
 76: 6,
 272: 6,
 1508: 6,
 2495: 6,
 80: 9,
 2492: 9,
 85: 5,
 273: 5,
 1760: 5,
 86: 19,
 155: 19,
 191: 19,
 372: 19,
 500: 19,
 1296: 19,
 1832: 19,
 1998: 19,
 3166: 19,
 368: 31,
 434: 16,
 460: 31,
 579: 31,
 1199: 31,
 1208: 22,
 1336: 5,
 1431: 19,
 1717: 31,
 2061: 31,
 2410: 9,
 2426: 31,
 2636: 31,
 3481: 9,
 3482: 9,
 90: 19,
 1532: 3,
 1682: 5,
 1699: 19,
 91: 5,
 1445: 5,
 1592: 5,
 102: 3,
 561: 3,
 1212: 3,
 104: 12,
 105: 12,
 107: 9,
 268: 9,
 952: 9,
 3375: 9,
 108: 30,
 501: 30,
 778: 30,
 895: 30,
 1759: 30,
 112: 1,
 115: 6,
 1073: 6,
 2193: 6,
 3503: 6,
 3504: 6,
 119: 13,
 730: 13,
 1603: 13,
 1726: 18,
 2858: 13,
 121: 1,
 1290: 1,
 1645: 1,
 2907: 1,
 3144: 1,
 126: 34,
 638: 19,
 733: 34,
 876: 34,
 1099: 34,
 1408: 34,
 1409: 34,
 131: 8,
 341: 8,
 747: 8,
 750: 8,
 751: 8,
 791: 8,
 133: 3,
 1529: 3,
 1804: 3,
 134: 6,
 2873: 6,
 135: 27,
 2793: 27,
 2794: 27,
 2819: 27,
 3031: 27,
 3383: 27,
 3391: 27,
 136: 9,
 1599: 9,
 2406: 9,
 137: 1,
 139: 18,
 1970: 18,
 2088: 18,
 140: 12,
 3058: 12,
 142: 5,
 181: 5,
 355: 5,
 356: 5,
 458: 5,
 785: 5,
 837: 5,
 983: 5,
 1035: 5,
 1528: 5,
 143: 30,
 2147: 30,
 3389: 30,
 149: 17,
 228: 17,
 311: 17,
 466: 10,
 765: 17,
 807: 17,
 917: 17,
 1013: 17,
 1129: 17,
 1131: 17,
 1132: 17,
 1160: 23,
 1795: 17,
 2820: 17,
 150: 1,
 1452: 1,
 151: 1,
 2239: 1,
 2657: 1,
 2913: 1,
 153: 9,
 797: 9,
 156: 5,
 1364: 5,
 1626: 5,
 1677: 5,
 1817: 5,
 157: 15,
 3200: 15,
 158: 3,
 1018: 3,
 2480: 3,
 159: 2,
 1369: 2,
 1444: 2,
 3024: 11,
 162: 35,
 242: 35,
 721: 35,
 729: 35,
 1728: 35,
 164: 7,
 1240: 7,
 1491: 7,
 169: 32,
 576: 32,
 1510: 32,
 1531: 32,
 1542: 32,
 1634: 32,
 2477: 32,
 170: 3,
 313: 3,
 1530: 3,
 2778: 3,
 172: 24,
 677: 24,
 694: 24,
 1610: 24,
 173: 1,
 1812: 1,
 3038: 1,
 3121: 1,
 3279: 1,
 174: 10,
 408: 10,
 1076: 10,
 1101: 10,
 1550: 10,
 1673: 10,
 176: 1,
 2961: 16,
 178: 2,
 1365: 2,
 179: 23,
 858: 5,
 2969: 23,
 3275: 23,
 198: 1,
 432: 5,
 435: 5,
 536: 5,
 656: 5,
 897: 5,
 984: 5,
 1003: 5,
 1123: 5,
 1451: 5,
 187: 9,
 428: 9,
 189: 22,
 815: 22,
 839: 22,
 1320: 22,
 1791: 22,
 1853: 22,
 190: 9,
 194: 21,
 907: 21,
 1049: 21,
 2679: 21,
 195: 10,
 773: 10,
 1040: 10,
 1186: 10,
 1410: 10,
 2776: 10,
 202: 1,
 203: 14,
 395: 14,
 516: 14,
 570: 14,
 589: 14,
 800: 14,
 207: 23,
 782: 23,
 1762: 23,
 2786: 23,
 210: 21,
 2021: 21,
 211: 9,
 231: 9,
 2027: 9,
 212: 2,
 1739: 2,
 2760: 2,
 213: 24,
 1811: 24,
 3168: 24,
 223: 20,
 565: 20,
 1173: 20,
 1250: 20,
 225: 7,
 1485: 1,
 3068: 7,
 226: 19,
 944: 26,
 1128: 4,
 1156: 26,
 1315: 26,
 1358: 26,
 1669: 10,
 1796: 26,
 1797: 26,
 271: 17,
 504: 17,
 995: 17,
 1159: 17,
 1637: 17,
 1641: 17,
 1672: 17,
 1700: 17,
 1849: 17,
 2175: 17,
 229: 10,
 1042: 10,
 1330: 10,
 495: 9,
 544: 9,
 605: 9,
 982: 9,
 3395: 9,
 233: 6,
 1000: 6,
 1935: 6,
 3015: 6,
 235: 34,
 543: 34,
 1424: 34,
 237: 9,
 525: 9,
 238: 15,
 293: 15,
 580: 15,
 244: 17,
 1334: 15,
 245: 26,
 370: 26,
 986: 26,
 1554: 26,
 1612: 4,
 1846: 26,
 250: 17,
 1252: 17,
 1713: 17,
 251: 2,
 1023: 2,
 2006: 2,
 2429: 2,
 252: 5,
 366: 5,
 440: 5,
 477: 5,
 595: 5,
 612: 5,
 254: 13,
 255: 25,
 2812: 25,
 3206: 25,
 3475: 25,
 256: 18,
 1370: 18,
 1856: 18,
 1857: 18,
 1858: 18,
 262: 29,
 488: 29,
 490: 29,
 521: 29,
 746: 29,
 263: 1,
 981: 1,
 269: 6,
 2583: 6,
 3381: 6,
 270: 10,
 1041: 10,
 1319: 10,
 1127: 2,
 1742: 2,
 274: 30,
 2091: 30,
 3138: 30,
 276: 2,
 278: 3,
 945: 3,
 1502: 2,
 1835: 3,
 281: 22,
 538: 22,
 2933: 22,
 282: 14,
 1425: 14,
 3066: 14,
 283: 10,
 284: 5,
 505: 5,
 584: 5,
 833: 5,
 1271: 5,
 286: 19,
 1525: 19,
 287: 30,
 288: 18,
 1681: 18,
 289: 6,
 711: 7,
 2067: 6,
 296: 4,
 892: 4,
 1251: 4,
 297: 2,
 2277: 2,
 298: 23,
 299: 7,
 301: 7,
 2340: 7,
 3119: 7,
 302: 26,
 1977: 26,
 3034: 26,
 314: 19,
 315: 2,
 827: 2,
 2615: 2,
 317: 23,
 796: 23,
 819: 23,
 318: 18,
 324: 2,
 429: 10,
 523: 16,
 779: 2,
 809: 2,
 883: 2,
 1109: 2,
 1202: 2,
 1460: 2,
 1764: 2,
 1800: 2,
 2104: 2,
 2139: 2,
 2185: 2,
 2304: 2,
 2322: 2,
 2437: 11,
 2557: 2,
 2647: 2,
 2803: 2,
 3165: 2,
 3452: 4,
 321: 18,
 601: 18,
 603: 18,
 323: 15,
 2644: 15,
 2887: 15,
 2968: 15,
 3073: 15,
 3264: 15,
 330: 18,
 1172: 18,
 332: 27,
 1242: 27,
 334: 40,
 2737: 40,
 2802: 40,
 2814: 40,
 2815: 40,
 3101: 40,
 337: 13,
 3229: 13,
 340: 22,
 420: 22,
 1374: 22,
 1694: 22,
 1859: 22,
 2800: 22,
 1951: 8,
 342: 30,
 343: 30,
 1978: 30,
 344: 10,
 352: 7,
 353: 15,
 575: 15,
 2069: 15,
 2200: 15,
 2365: 15,
 410: 5,
 830: 5,
 1021: 5,
 1830: 5,
 358: 10,
 1551: 10,
 1552: 10,
 361: 35,
 1140: 35,
 1450: 35,
 362: 3,
 2258: 3,
 369: 30,
 378: 5,
 1435: 5,
 1440: 5,
 388: 8,
 885: 8,
 3022: 8,
 390: 10,
 1826: 10,
 472: 14,
 2008: 14,
 2764: 14,
 397: 2,
 455: 2,
 804: 2,
 954: 2,
 401: 4,
 684: 4,
 977: 4,
 1614: 4,
 402: 13,
 2214: 13,
 2224: 13,
 2571: 13,
 2921: 13,
 403: 21,
 1906: 21,
 3343: 21,
 406: 17,
 407: 18,
 3228: 13,
 416: 13,
 1232: 13,
 1273: 13,
 2222: 13,
 421: 10,
 1043: 10,
 422: 5,
 1163: 5,
 423: 15,
 426: 10,
 596: 4,
 639: 9,
 433: 10,
 431: 5,
 470: 5,
 906: 5,
 999: 5,
 1750: 5,
 2039: 5,
 2452: 5,
 552: 16,
 553: 16,
 896: 5,
 2062: 16,
 2152: 5,
 2677: 16,
 3346: 16,
 439: 15,
 454: 15,
 512: 15,
 1153: 15,
 443: 8,
 447: 3,
 3252: 3,
 452: 3,
 1734: 16,
 3329: 21,
 459: 32,
 2633: 32,
 461: 21,
 462: 21,
 1608: 21,
 640: 21,
 641: 21,
 2086: 21,
 463: 1,
 465: 10,
 2852: 10,
 2853: 10,
 1053: 10,
 1692: 16,
 2473: 10,
 2783: 10,
 2985: 10,
 471: 4,
 795: 4,
 1253: 4,
 1513: 4,
 1571: 4,
 474: 4,
 2024: 4,
 2901: 4,
 475: 8,
 478: 22,
 479: 22,
 572: 22,
 573: 22,
 1642: 22,
 484: 14,
 1447: 14,
 2409: 14,
 2701: 14,
 3246: 14,
 3276: 14,
 492: 10,
 493: 31,
 2662: 31,
 496: 33,
 1360: 33,
 1372: 33,
 1385: 33,
 748: 30,
 909: 17,
 993: 17,
 1054: 17,
 1380: 17,
 1462: 17,
 1568: 17,
 1707: 17,
 2038: 17,
 3258: 17,
 3491: 17,
 3494: 17,
 509: 31,
 680: 31,
 1815: 31,
 514: 10,
 1038: 10,
 1526: 10,
 1840: 10,
 1876: 10,
 910: 14,
 1047: 14,
 2324: 14,
 520: 2,
 843: 2,
 2528: 2,
 522: 3,
 2697: 16,
 526: 22,
 528: 3,
 581: 3,
 1511: 3,
 1704: 3,
 532: 32,
 1142: 32,
 535: 16,
 1693: 16,
 1916: 16,
 2628: 16,
 2719: 16,
 3023: 16,
 3067: 16,
 3396: 16,
 3462: 16,
 548: 3,
 549: 8,
 2255: 8,
 2476: 8,
 550: 14,
 1119: 16,
 1775: 16,
 554: 8,
 1044: 8,
 1301: 8,
 555: 32,
 1032: 32,
 1628: 32,
 557: 5,
 604: 5,
 559: 1,
 658: 1,
 3474: 1,
 564: 15,
 1138: 15,
 566: 9,
 2081: 9,
 571: 3,
 657: 7,
 686: 7,
 728: 3,
 847: 7,
 863: 31,
 879: 7,
 1189: 7,
 1190: 7,
 1191: 7,
 1298: 12,
 1346: 7,
 1546: 31,
 1619: 7,
 1653: 7,
 1743: 7,
 1820: 7,
 1844: 12,
 2003: 7,
 2082: 7,
 2590: 27,
 2635: 7,
 3026: 27,
 3056: 7,
 3410: 7,
 3077: 15,
 582: 22,
 1248: 22,
 1674: 5,
 1821: 22,
 583: 35,
 585: 5,
 1247: 4,
 1347: 5,
 591: 30,
 2004: 30,
 653: 4,
 965: 4,
 1587: 4,
 1736: 4,
 597: 10,
 1793: 38,
 1828: 10,
 598: 4,
 762: 4,
 1005: 4,
 600: 10,
 878: 10,
 610: 4,
 1201: 4,
 780: 5,
 613: 16,
 616: 16,
 856: 16,
 1058: 16,
 2449: 16,
 620: 1,
 650: 1,
 621: 41,
 2422: 41,
 2648: 41,
 2649: 41,
 627: 4,
 1613: 4,
 632: 2,
 859: 2,
 1671: 2,
 1702: 2,
 633: 5,
 958: 5,
 1774: 5,
 634: 12,
 2022: 12,
 3174: 12,
 2060: 9,
 2243: 9,
 2321: 34,
 2509: 9,
 644: 1,
 645: 1,
 646: 1,
 647: 8,
 700: 8,
 648: 20,
 1377: 20,
 1396: 20,
 649: 33,
 652: 6,
 3182: 6,
 832: 4,
 1946: 4,
 2366: 4,
 2833: 4,
 2976: 4,
 2977: 4,
 3062: 4,
 3088: 4,
 3124: 4,
 3451: 11,
 669: 18,
 674: 18,
 2632: 24,
 2664: 24,
 3115: 24,
 681: 8,
 687: 10,
 1484: 10,
 1536: 10,
 688: 9,
 689: 9,
 693: 25,
 1783: 25,
 696: 18,
 1860: 18,
 709: 4,
 793: 4,
 886: 4,
 912: 4,
 998: 4,
 1052: 4,
 1406: 4,
 1654: 4,
 1831: 4,
 2493: 4,
 698: 2,
 699: 13,
 971: 13,
 3040: 13,
 701: 21,
 3345: 21,
 703: 20,
 1459: 20,
 706: 29,
 2501: 29,
 708: 5,
 1147: 5,
 3146: 5,
 717: 6,
 2357: 6,
 3238: 6,
 720: 22,
 722: 5,
 1569: 5,
 1675: 5,
 1676: 5,
 749: 3,
 3356: 3,
 731: 1,
 732: 2,
 2350: 34,
 3061: 34,
 734: 18,
 1519: 18,
 2158: 18,
 2189: 18,
 735: 28,
 1985: 28,
 2608: 28,
 738: 18,
 1650: 18,
 1861: 18,
 739: 9,
 741: 10,
 1428: 29,
 761: 2,
 1166: 2,
 763: 2,
 766: 27,
 1871: 27,
 1873: 27,
 2156: 12,
 767: 7,
 774: 1,
 1449: 1,
 777: 39,
 2268: 39,
 1882: 2,
 781: 12,
 867: 23,
 2856: 23,
 3288: 23,
 788: 19,
 1056: 19,
 1196: 19,
 3347: 19,
 790: 3,
 1779: 3,
 1990: 3,
 1991: 3,
 1808: 8,
 792: 2,
 798: 12,
 806: 12,
 1481: 12,
 2042: 12,
 2582: 12,
 801: 6,
 2382: 6,
 869: 2,
 1276: 2,
 3100: 35,
 803: 6,
 1794: 2,
 2326: 2,
 3248: 12,
 805: 20,
 1517: 20,
 2958: 17,
 2181: 2,
 2606: 2,
 1009: 2,
 1453: 2,
 2575: 14,
 814: 6,
 818: 33,
 1348: 33,
 822: 10,
 823: 10,
 1107: 10,
 824: 23,
 888: 23,
 825: 23,
 826: 23,
 828: 2,
 829: 2,
 1661: 2,
 1662: 2,
 3112: 2,
 3239: 2,
 834: 12,
 2588: 12,
 2728: 12,
 2934: 12,
 3480: 12,
 838: 5,
 841: 1,
 1187: 38,
 1289: 38,
 1588: 38,
 1683: 38,
 2221: 38,
 3299: 38,
 848: 8,
 849: 8,
 2641: 8,
 2643: 8,
 850: 10,
 855: 3,
 857: 2,
 865: 18,
 ...}

In [39]:
for e in data['links']:
    if gn_comms[e['source']] == gn_comms[e['target']]:
        e['color'] = gn_comms[e['source']]
    else:
        e['color'] = 0

In [ ]:
data

In [20]:
with open('GirvanNewman.json', 'w') as json_file:
    json.dump(data, json_file)

In [41]:
from networkx.readwrite import json_graph

GN = json_graph.node_link_graph(data)

In [42]:
degs = {}
for i in GN.nodes:
    degs[i] = GN.degree[i]

In [43]:
import networkx as nx
nx.set_node_attributes(GN, degs, 'Degree')

In [44]:
GN_data = json_graph.node_link_data(GN)

In [45]:
with open('GirvanNewman.json', 'w') as json_file:
    json.dump(GN_data, json_file)